# Generated by Django 5.2.17 on 2026-09-07 17:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import report.crypto_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPERUSER", "Superuser"),
                            ("ADMIN", "Admin / SPV"),
                            ("SALES", "Sales"),
                            ("TEKNISI", "Teknisi"),
                        ],
                        default="SALES",
                        max_length=20,
                    ),
                ),
                (
                    "no_hp",
                    models.CharField(blank=True, max_length=20, verbose_name="No. HP"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Instansi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=150)),
                ("alamat", report.crypto_fields.EncryptedTextField(blank=True)),
                (
                    "pic",
                    report.crypto_fields.EncryptedCharField(
                        blank=True, max_length=100, verbose_name="PIC"
                    ),
                ),
                (
                    "no_wa",
                    report.crypto_fields.EncryptedCharField(
                        blank=True, max_length=20, verbose_name="No. WhatsApp"
                    ),
                ),
                ("dibuat_pada", models.DateTimeField(auto_now_add=True)),
                (
                    "dibuat_oleh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instansi_dibuat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Instansi",
                "ordering": ["nama"],
            },
        ),
        migrations.CreateModel(
            name="Kunjungan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BARU", "Baru"),
                            ("PEMBICARAAN", "Pembicaraan"),
                            ("PENAWARAN", "Penawaran"),
                            ("CLOSING", "Closing"),
                            ("TIDAK_RESPON", "Tidak Respon"),
                            ("BATAL", "Batal"),
                        ],
                        default="BARU",
                        max_length=20,
                    ),
                ),
                (
                    "tahap",
                    models.CharField(
                        choices=[
                            ("AWAL", "Kunjungan Awal"),
                            ("FOLLOW_UP", "Follow Up"),
                            ("PROGRESS", "Progress"),
                        ],
                        default="AWAL",
                        max_length=20,
                    ),
                ),
                ("catatan", report.crypto_fields.EncryptedTextField(blank=True)),
                ("dibuat_pada", models.DateTimeField(auto_now_add=True)),
                ("diubah_pada", models.DateTimeField(auto_now=True)),
                (
                    "instansi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kunjungan",
                        to="report.instansi",
                    ),
                ),
                (
                    "sales",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kunjungan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Kunjungan",
                "ordering": ["-tanggal", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FollowUpWA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jenis",
                    models.CharField(
                        choices=[
                            ("H0", "H0 - Terima kasih"),
                            ("H2", "H2 - Follow up"),
                            ("H5", "H5 - Penawaran"),
                        ],
                        max_length=2,
                    ),
                ),
                ("waktu", models.DateTimeField(auto_now_add=True)),
                ("pesan", models.TextField(blank=True)),
                (
                    "oleh",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="followup_wa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kunjungan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followup",
                        to="report.kunjungan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Follow Up WA",
                "verbose_name_plural": "Follow Up WA",
                "ordering": ["waktu"],
            },
        ),
        migrations.AddConstraint(
            model_name="instansi",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("nama"),
                name="instansi_nama_unik_ci",
            ),
        ),
    ]
